spring:
  profiles:
    active: test

server:
  port: 80

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  #  org.hibernate.SQL: debug
  org.hibernate.type: trace

intranet:
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/fourfree_intranet
      username: root
      password:
